import os

Import('env')
Import('libtype')

if libtype == 'static':
    libBioLCCC_static = env.StaticLibrary(
        target = '#'+os.path.join('lib', 'static',
            env['PLATFORM'], env['BUILDTYPE'],'libBioLCCC'),
        source = Glob('*.cpp'))

    Return('libBioLCCC_static')

if libtype == 'shared':
    libBioLCCC_shared = env.SharedLibrary(
        target = '#'+os.path.join('lib', 'shared',
            env['PLATFORM'], env['BUILDTYPE'],'libBioLCCC'),
        source = Glob('*.cpp'))

    Return('libBioLCCC_shared')

