import os

Import('env')

libBioLCCC_static = env.StaticLibrary(
    target = '#'+os.path.join('lib', 'static',
        env['PLATFORM'], env['BUILDTYPE'],'libBioLCCC'),
    source = Glob('*.cpp'))

Return('libBioLCCC_static')
