name: Upload Python Package

on:
 release:
  types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.4.0-manylinux_2_24_x86_64
      with:
        system-packages: 'swig3'
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
        pre-build-command: 'python build.py -b build pyteomics.biolccc && cd build'
        pip-wheel-args:
    - name: Upload wheels and source distribution
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*-manylinux*.whl
        python setup.py sdist
        twine upload dist/*.tar.gz
